#!/usr/bin/env bash
# Post-pull activation: build, test, deploy skill into OpenClaw workspace, write env file.
# Run from repo root (or via npm run activate). Requires OPENCLAW_WORKSPACE when repo is not under workspace/repositories/router-governor.

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

# Resolve OpenClaw workspace root (contains skills/, repositories/, etc.)
if [ -n "$OPENCLAW_WORKSPACE" ]; then
  if [ -d "$OPENCLAW_WORKSPACE" ]; then
    OPENCLAW_WORKSPACE="$(cd "$OPENCLAW_WORKSPACE" && pwd)"
  fi
elif [[ "$REPO_ROOT" == */repositories/router-governor ]] || [[ "$REPO_ROOT" == */repositories/model-governor-skill ]]; then
  OPENCLAW_WORKSPACE="$(cd "$REPO_ROOT/../.." && pwd)"
else
  echo "ERROR: OPENCLAW_WORKSPACE not set and repo is not at .../workspace/repositories/router-governor (or model-governor-skill)"
  echo "Set it to your OpenClaw workspace root, e.g.:"
  echo "  export OPENCLAW_WORKSPACE=/path/to/.openclaw/workspace"
  exit 1
fi

OPENCLAW_HOME="$(cd "$OPENCLAW_WORKSPACE/.." && pwd)"
SKILLS_DIR="$OPENCLAW_WORKSPACE/skills"
SKILL_DEST="$SKILLS_DIR/router-governor"
ENV_FILE="$OPENCLAW_WORKSPACE/.env.router-governor"
SYSTEMD_ENV_FILE="$OPENCLAW_WORKSPACE/.env.router-governor.systemd"

# Create workspace dirs if we're deploying into a new workspace
mkdir -p "$SKILLS_DIR"

echo "Repo root:      $REPO_ROOT"
echo "Workspace:      $OPENCLAW_WORKSPACE"
echo "OpenClaw home:  $OPENCLAW_HOME"
echo "Skill dest:     $SKILL_DEST"

# Build and test
echo "--- npm install"
npm install
echo "--- npm run build"
npm run build
echo "--- npm test"
npm test

# Deploy skill so OpenClaw loads it when router is selected
mkdir -p "$SKILL_DEST"
cp -r "$REPO_ROOT/skills/router-governor/"* "$SKILL_DEST/"
echo "--- Deployed skill to $SKILL_DEST"

# Env file for the process that runs OpenClaw (or the governor bridge)
# Source before starting OpenClaw so governor code and log-report use correct paths
cat > "$ENV_FILE" << EOF
# Router-governor paths — source before starting OpenClaw or running bridge/log-report
# Generated by scripts/post-pull-activate.sh — do not edit by hand
export OPENCLAW_HOME="$OPENCLAW_HOME"
export ROUTER_GOVERNOR_POLICY_PATH="$REPO_ROOT/config/policy.json"
# Log path defaults to OPENCLAW_HOME/logs/model-governor.jsonl when OPENCLAW_HOME is set
# Override if needed: export ROUTER_GOVERNOR_LOG_PATH=/path/to/model-governor.jsonl
EOF
echo "--- Wrote $ENV_FILE"

# Systemd-compatible env file (EnvironmentFile=... expects KEY=VALUE, not 'export KEY=VALUE')
cat > "$SYSTEMD_ENV_FILE" << EOF
OPENCLAW_HOME=$OPENCLAW_HOME
ROUTER_GOVERNOR_POLICY_PATH=$REPO_ROOT/config/policy.json
# ROUTER_GOVERNOR_LOG_PATH=/path/to/model-governor.jsonl
EOF
echo "--- Wrote $SYSTEMD_ENV_FILE"

# If the gateway runs as a user-level systemd service, wire env and restart automatically.
if systemctl --user status openclaw-gateway.service >/dev/null 2>&1; then
  OVERRIDE_DIR="$HOME/.config/systemd/user/openclaw-gateway.service.d"
  OVERRIDE_FILE="$OVERRIDE_DIR/override.conf"
  mkdir -p "$OVERRIDE_DIR"

  if [ -f "$OVERRIDE_FILE" ]; then
    awk '!/^\s*EnvironmentFile=-\/root\/openclaw-stock-home\/\.openclaw\/workspace\/\.env\.router-governor(\.systemd)?\s*$/' "$OVERRIDE_FILE" > "${OVERRIDE_FILE}.tmp"
    mv "${OVERRIDE_FILE}.tmp" "$OVERRIDE_FILE"
  else
    printf "[Service]\n" > "$OVERRIDE_FILE"
  fi

  printf "EnvironmentFile=-%s\n" "$SYSTEMD_ENV_FILE" >> "$OVERRIDE_FILE"
  # Run gateway on backend port so proxy can listen on public port
  if ! grep -q 'OPENCLAW_GATEWAY_PORT=18790' "$OVERRIDE_FILE"; then
    printf "Environment=OPENCLAW_GATEWAY_PORT=18790\n" >> "$OVERRIDE_FILE"
  fi
  systemctl --user daemon-reload
  systemctl --user restart openclaw-gateway.service
  echo "--- Wired $SYSTEMD_ENV_FILE into openclaw-gateway.service, gateway port 18790, restarted"

  # Install and start gateway proxy so router model requests go through governor
  PROXY_UNIT="$HOME/.config/systemd/user/openclaw-gateway-proxy.service"
  PROXY_OVERRIDE_DIR="$HOME/.config/systemd/user/openclaw-gateway-proxy.service.d"
  mkdir -p "$PROXY_OVERRIDE_DIR"
  sed "s|%REPO_ROOT%|$REPO_ROOT|g" "$REPO_ROOT/scripts/systemd/openclaw-gateway-proxy.service" > "$PROXY_UNIT"
  printf "[Service]\nEnvironmentFile=-%s\n" "$SYSTEMD_ENV_FILE" > "$PROXY_OVERRIDE_DIR/override.conf"
  systemctl --user daemon-reload
  systemctl --user enable openclaw-gateway-proxy.service
  systemctl --user start openclaw-gateway-proxy.service
  echo "--- Installed and started openclaw-gateway-proxy.service (listens 18789, forwards to gateway 18790)"
fi

echo ""
echo "Activation done. Router-governor is active when:"
echo "  1. Skill is in workspace/skills/router-governor (done above)."
echo "  2. openclaw-gateway runs with governor env and port 18790; openclaw-gateway-proxy listens on 18789 and runs governor for model=router (done above if gateway service exists)."
echo "  3. Run log report: source $ENV_FILE && npm run log:report (from this repo)."
