#!/usr/bin/env bash
# Post-pull activation: build, test, deploy skill, set up gateway proxy, wire Caddy.
# Reads gateway.port from openclaw.json. Public port = gateway.port (proxy); backend = port+1 (actual openclaw process).
#
# Usage:
#   npm run activate                         (auto-detects workspace under .../workspace/repositories/)
#   OPENCLAW_WORKSPACE=/path npm run activate (when repo lives elsewhere)

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

# ─── Resolve OpenClaw workspace ──────────────────────────────────────────────
if [ -n "$OPENCLAW_WORKSPACE" ]; then
  [ -d "$OPENCLAW_WORKSPACE" ] && OPENCLAW_WORKSPACE="$(cd "$OPENCLAW_WORKSPACE" && pwd)"
elif [[ "$REPO_ROOT" == */repositories/router-governor ]] ||
     [[ "$REPO_ROOT" == */repositories/model-governor-skill ]]; then
  OPENCLAW_WORKSPACE="$(cd "$REPO_ROOT/../.." && pwd)"
else
  echo "ERROR: OPENCLAW_WORKSPACE not set and repo is not at .../workspace/repositories/router-governor (or model-governor-skill)"
  echo "Set: export OPENCLAW_WORKSPACE=/path/to/.openclaw/workspace"
  exit 1
fi

OPENCLAW_HOME="$(cd "$OPENCLAW_WORKSPACE/.." && pwd)"
SKILLS_DIR="$OPENCLAW_WORKSPACE/skills"
SKILL_DEST="$SKILLS_DIR/router-governor"
ENV_FILE="$OPENCLAW_WORKSPACE/.env.router-governor"
SYSTEMD_ENV_FILE="$OPENCLAW_WORKSPACE/.env.router-governor.systemd"
WS_SCRIPTS="$OPENCLAW_WORKSPACE/scripts"
GATEWAY_SCRIPT="$WS_SCRIPTS/run-gateway.sh"
VALIDATE_SCRIPT="$WS_SCRIPTS/validate-gateway-proxy.sh"
mkdir -p "$WS_SCRIPTS" "$SKILLS_DIR"

echo "Repo root:      $REPO_ROOT"
echo "Workspace:      $OPENCLAW_WORKSPACE"
echo "OpenClaw home:  $OPENCLAW_HOME"

# ─── Read gateway.port from openclaw.json ────────────────────────────────────
# Public port  = gateway.port (proxy listens here; Caddy points here)
# Backend port = gateway.port + 1 (actual openclaw process listens here)
OC_CONFIG="${OPENCLAW_CONFIG_PATH:-$OPENCLAW_HOME/openclaw.json}"
if [ -f "$OC_CONFIG" ]; then
  GATEWAY_PUBLIC_PORT=$(node -e "
    try {
      const j = require('$OC_CONFIG');
      const p = j.gateway && j.gateway.port;
      process.stdout.write(typeof p === 'number' ? String(p) : '18789');
    } catch (e) { process.stdout.write('18789'); }
  " 2>/dev/null) || GATEWAY_PUBLIC_PORT=18789
else
  echo "WARNING: $OC_CONFIG not found; defaulting gateway.port to 18789"
  GATEWAY_PUBLIC_PORT=18789
fi
GATEWAY_BACKEND_PORT=$((GATEWAY_PUBLIC_PORT + 1))

echo "Public port  (proxy):   $GATEWAY_PUBLIC_PORT  ← Caddy + clients"
echo "Backend port (gateway): $GATEWAY_BACKEND_PORT  ← openclaw process"

# ─── Build and test ──────────────────────────────────────────────────────────
echo "--- npm install"
npm install
echo "--- npm run build"
npm run build
echo "--- npm test"
npm test

# ─── Deploy skill ────────────────────────────────────────────────────────────
mkdir -p "$SKILL_DEST"
cp -r "$REPO_ROOT/skills/router-governor/"* "$SKILL_DEST/"
echo "--- Deployed skill to $SKILL_DEST"

# ─── Env files ───────────────────────────────────────────────────────────────
cat > "$ENV_FILE" << EOF
# Router-governor env (shell) — generated by scripts/post-pull-activate.sh — do not edit by hand
export OPENCLAW_HOME="$OPENCLAW_HOME"
export ROUTER_GOVERNOR_POLICY_PATH="$REPO_ROOT/config/policy.json"
# Log path defaults to OPENCLAW_HOME/logs/model-governor.jsonl
EOF

cat > "$SYSTEMD_ENV_FILE" << EOF
OPENCLAW_HOME=$OPENCLAW_HOME
ROUTER_GOVERNOR_POLICY_PATH=$REPO_ROOT/config/policy.json
EOF
echo "--- Wrote env files"

# ─── run-gateway.sh (single source of truth: reads openclaw.json at start time) ─
# Runs openclaw gateway on backend port (gateway.port + 1) so proxy can own the public port.
cat > "$GATEWAY_SCRIPT" << 'GWEOF'
#!/bin/sh
# Run openclaw gateway on (gateway.port + 1) so the router-governor proxy owns gateway.port.
# Single source of truth: openclaw.json → gateway.port.
CONFIG="${OPENCLAW_CONFIG_PATH:-${OPENCLAW_HOME:-$HOME/.openclaw}/openclaw.json}"
PUBLIC_PORT=$(node -e "
  try {
    const j = require(\"$CONFIG\");
    const p = j.gateway && j.gateway.port;
    process.stdout.write(typeof p === 'number' ? String(p) : '18789');
  } catch (e) { process.stdout.write('18789'); }
" 2>/dev/null) || PUBLIC_PORT=18789
BACKEND_PORT=$((PUBLIC_PORT + 1))
exec /usr/bin/node /usr/lib/node_modules/openclaw/dist/index.js gateway --port "$BACKEND_PORT"
GWEOF
chmod +x "$GATEWAY_SCRIPT"
echo "--- Wrote $GATEWAY_SCRIPT"

# ─── validate-gateway-proxy.sh ───────────────────────────────────────────────
cat > "$VALIDATE_SCRIPT" << 'VEOF'
#!/bin/sh
# Validate the router-governor proxy → openclaw gateway → Caddy port chain.
CONFIG="${OPENCLAW_CONFIG_PATH:-${OPENCLAW_HOME:-$HOME/.openclaw}/openclaw.json}"
PUBLIC=$(node -e "
  try { const j=require(\"$CONFIG\"); process.stdout.write(String(j.gateway&&j.gateway.port||18789)); }
  catch(e){ process.stdout.write('18789'); }
" 2>/dev/null) || PUBLIC=18789
BACKEND=$((PUBLIC + 1))
FAIL=0

echo "Config:  $CONFIG  (gateway.port = $PUBLIC)"
echo "Chain:   Caddy → proxy :$PUBLIC → gateway :$BACKEND"
echo ""

# Unsupported key: agents.defaults.skills (OpenClaw rejects it; gateway won't start)
if [ -n "$CONFIG" ] && [ -f "$CONFIG" ]; then
  if CONFIG="$CONFIG" node -e '
    try {
      const j = require(process.env.CONFIG);
      const s = j && j.agents && j.agents.defaults && j.agents.defaults.skills;
      process.exit(typeof s !== "undefined" ? 0 : 1);
    } catch (e) { process.exit(1); }
  ' 2>/dev/null; then
    echo "  [FAIL] openclaw.json contains agents.defaults.skills (unsupported; gateway will not start)"
    echo "         Remove that key (e.g. openclaw doctor --fix or edit manually), then restart gateway."
    FAIL=1
  fi
fi

# Proxy
if ss -tlnp 2>/dev/null | grep -q ":${PUBLIC}[^0-9]"; then
  echo "  [OK]   proxy listening on :$PUBLIC"
else
  echo "  [FAIL] proxy not listening on :$PUBLIC"
  FAIL=1
fi
# Gateway
if ss -tlnp 2>/dev/null | grep -q ":${BACKEND}[^0-9]"; then
  echo "  [OK]   gateway listening on :$BACKEND"
else
  echo "  [FAIL] gateway not listening on :$BACKEND"
  FAIL=1
fi
# Caddy
CADDY_OK=0
for CF in /etc/caddy/Caddyfile /usr/local/etc/caddy/Caddyfile; do
  [ -f "$CF" ] || continue
  if grep -q "reverse_proxy.*127\.0\.0\.1:${PUBLIC}[^0-9]" "$CF" 2>/dev/null; then
    echo "  [OK]   Caddy ($CF) → :$PUBLIC"
    CADDY_OK=1
  else
    ACTUAL=$(grep -o 'reverse_proxy [^ {:]*' "$CF" 2>/dev/null | head -1 | awk '{print $2}')
    echo "  [FAIL] Caddy ($CF) → $ACTUAL (expected 127.0.0.1:$PUBLIC)"
    FAIL=1
  fi
done
[ "$CADDY_OK" -eq 0 ] && echo "  [SKIP] Caddy not found or no Caddyfile"

# Health endpoint
HEALTH=$(curl -s --max-time 2 "http://127.0.0.1:${PUBLIC}/health" 2>/dev/null || echo "")
if echo "$HEALTH" | grep -q '"status":"ok"'; then
  echo "  [OK]   proxy /health"
else
  echo "  [WARN] proxy /health returned: $HEALTH"
fi

echo ""
[ "$FAIL" -eq 0 ] && echo "All checks passed." || echo "Fix the failures above."
exit $FAIL
VEOF
chmod +x "$VALIDATE_SCRIPT"
echo "--- Wrote $VALIDATE_SCRIPT"

# ─── systemd wiring ──────────────────────────────────────────────────────────
if ! systemctl --user status openclaw-gateway.service >/dev/null 2>&1; then
  echo "--- openclaw-gateway.service not found; skipping systemd wiring"
else
  # Refuse to activate if openclaw.json contains unsupported agents.defaults.skills (gateway won't start)
  if [ -f "$OC_CONFIG" ]; then
    if node -e "
      try {
        const j = require('$OC_CONFIG');
        const s = j && j.agents && j.agents.defaults && j.agents.defaults.skills;
        process.exit(typeof s !== 'undefined' ? 0 : 1);
      } catch (e) { process.exit(1); }
    " 2>/dev/null; then
      echo "ERROR: $OC_CONFIG contains agents.defaults.skills. OpenClaw does not support this key; the gateway will not start."
      echo "Remove it (e.g. openclaw doctor --fix or edit manually), then run npm run activate again."
      exit 1
    fi
  fi

  OVERRIDE_DIR="$HOME/.config/systemd/user/openclaw-gateway.service.d"
  OVERRIDE_FILE="$OVERRIDE_DIR/override.conf"
  mkdir -p "$OVERRIDE_DIR"

  # Strip lines we own; preserve hand-crafted lines from the existing override
  if [ -f "$OVERRIDE_FILE" ]; then
    awk '
      /^\s*ExecStart=/                    { next }
      /^\s*EnvironmentFile=.*router-governor/ { next }
      /^\s*Environment=OPENCLAW_GATEWAY_PORT=/ { next }
      { print }
    ' "$OVERRIDE_FILE" > "${OVERRIDE_FILE}.tmp"
    mv "${OVERRIDE_FILE}.tmp" "$OVERRIDE_FILE"
  else
    printf "[Service]\n" > "$OVERRIDE_FILE"
  fi

  # Append our controlled lines
  cat >> "$OVERRIDE_FILE" << EOV
EnvironmentFile=-$SYSTEMD_ENV_FILE
# ExecStart= clears the main unit's ExecStart (systemd requires exactly one)
ExecStart=
ExecStart=$GATEWAY_SCRIPT
EOV

  systemctl --user daemon-reload
  systemctl --user restart openclaw-gateway.service
  echo "--- Gateway restarted (port $GATEWAY_BACKEND_PORT via $GATEWAY_SCRIPT)"

  # ─── Proxy service ───────────────────────────────────────────────────────
  PROXY_UNIT="$HOME/.config/systemd/user/openclaw-gateway-proxy.service"
  PROXY_OVERRIDE_DIR="$HOME/.config/systemd/user/openclaw-gateway-proxy.service.d"
  mkdir -p "$PROXY_OVERRIDE_DIR"

  # Write proxy unit with concrete paths and ports (re-generated each time)
  cat > "$PROXY_UNIT" << PEOF
[Unit]
Description=OpenClaw Gateway Proxy (router-governor)
After=openclaw-gateway.service

[Service]
Environment=OPENCLAW_GATEWAY_PROXY_PORT=$GATEWAY_PUBLIC_PORT
Environment=OPENCLAW_GATEWAY_BACKEND_URL=http://127.0.0.1:$GATEWAY_BACKEND_PORT
WorkingDirectory=$REPO_ROOT
ExecStart=/usr/bin/node $REPO_ROOT/dist/src/gateway-proxy.js
Restart=always
RestartSec=5

[Install]
WantedBy=default.target
PEOF

  printf "[Service]\nEnvironmentFile=-%s\n" "$SYSTEMD_ENV_FILE" > "$PROXY_OVERRIDE_DIR/override.conf"
  systemctl --user daemon-reload
  systemctl --user enable openclaw-gateway-proxy.service
  systemctl --user restart openclaw-gateway-proxy.service
  echo "--- Proxy restarted (port $GATEWAY_PUBLIC_PORT → backend $GATEWAY_BACKEND_PORT)"
fi

# ─── Caddy: ensure it points to the proxy port (not the backend) ─────────────
for CADDYFILE in /etc/caddy/Caddyfile /usr/local/etc/caddy/Caddyfile; do
  [ -f "$CADDYFILE" ] || continue
  NEEDS_RELOAD=0
  # If Caddy is pointing directly at the backend port, redirect it to the proxy port
  if grep -q "reverse_proxy.*127\.0\.0\.1:${GATEWAY_BACKEND_PORT}" "$CADDYFILE"; then
    sed -i "s|reverse_proxy 127\.0\.0\.1:${GATEWAY_BACKEND_PORT}|reverse_proxy 127.0.0.1:${GATEWAY_PUBLIC_PORT}|g" "$CADDYFILE"
    echo "--- Updated Caddy ($CADDYFILE): :$GATEWAY_BACKEND_PORT → :$GATEWAY_PUBLIC_PORT"
    NEEDS_RELOAD=1
  elif grep -q "reverse_proxy.*127\.0\.0\.1:${GATEWAY_PUBLIC_PORT}" "$CADDYFILE"; then
    echo "--- Caddy ($CADDYFILE) already points to :$GATEWAY_PUBLIC_PORT [OK]"
  else
    echo "--- WARNING: Caddy found at $CADDYFILE but no matching reverse_proxy; check manually"
  fi
  if [ "$NEEDS_RELOAD" -eq 1 ]; then
    if command -v caddy >/dev/null 2>&1 && caddy reload --config "$CADDYFILE" 2>/dev/null; then
      echo "--- Caddy reloaded"
    elif systemctl reload caddy 2>/dev/null; then
      echo "--- Caddy reloaded (systemctl)"
    else
      echo "--- WARNING: Caddy reload failed; run: systemctl reload caddy"
    fi
  fi
done

echo ""
echo "Activation complete."
echo "  proxy  :$GATEWAY_PUBLIC_PORT  → governor (router) or forward to gateway"
echo "  gateway:$GATEWAY_BACKEND_PORT ← proxy forwards non-router traffic"
echo "  Caddy  → :$GATEWAY_PUBLIC_PORT (proxy)"
echo "  Validate: $VALIDATE_SCRIPT"
echo "  Logs:     source $ENV_FILE && npm run log:report"
