#!/usr/bin/env bash
# Post-pull activation: build, test, deploy skill, set up gateway proxy, wire Caddy.
# Reads gateway.port from openclaw.json. Public port = gateway.port (proxy); backend = port+1 (actual openclaw process).
#
# Usage:
#   npm run activate                         (auto-detects workspace under .../workspace/repositories/)
#   OPENCLAW_WORKSPACE=/path npm run activate (when repo lives elsewhere)

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

# ─── Resolve OpenClaw workspace ──────────────────────────────────────────────
if [ -n "$OPENCLAW_WORKSPACE" ]; then
  [ -d "$OPENCLAW_WORKSPACE" ] && OPENCLAW_WORKSPACE="$(cd "$OPENCLAW_WORKSPACE" && pwd)"
elif [[ "$REPO_ROOT" == */repositories/router-governor ]] ||
     [[ "$REPO_ROOT" == */repositories/model-governor-skill ]]; then
  OPENCLAW_WORKSPACE="$(cd "$REPO_ROOT/../.." && pwd)"
else
  echo "ERROR: OPENCLAW_WORKSPACE not set and repo is not at .../workspace/repositories/router-governor (or model-governor-skill)"
  echo "Set: export OPENCLAW_WORKSPACE=/path/to/.openclaw/workspace"
  exit 1
fi

OPENCLAW_HOME="$(cd "$OPENCLAW_WORKSPACE/.." && pwd)"
SKILLS_DIR="$OPENCLAW_WORKSPACE/skills"
SKILL_DEST="$SKILLS_DIR/router-governor"
ENV_FILE="$OPENCLAW_WORKSPACE/.env.router-governor"
SYSTEMD_ENV_FILE="$OPENCLAW_WORKSPACE/.env.router-governor.systemd"
WS_SCRIPTS="$OPENCLAW_WORKSPACE/scripts"
GATEWAY_SCRIPT="$WS_SCRIPTS/run-gateway.sh"
VALIDATE_SCRIPT="$WS_SCRIPTS/validate-gateway-proxy.sh"
mkdir -p "$WS_SCRIPTS" "$SKILLS_DIR"

echo "Repo root:      $REPO_ROOT"
echo "Workspace:      $OPENCLAW_WORKSPACE"
echo "OpenClaw home:  $OPENCLAW_HOME"

# ─── Read gateway.port from openclaw.json ────────────────────────────────────
# Public port  = gateway.port (proxy listens here; Caddy points here)
# Backend port = gateway.port + 1 (actual openclaw process listens here)
OC_CONFIG="${OPENCLAW_CONFIG_PATH:-$OPENCLAW_HOME/openclaw.json}"
if [ -f "$OC_CONFIG" ]; then
  GATEWAY_PUBLIC_PORT=$(node -e "
    try {
      const j = require('$OC_CONFIG');
      const p = j.gateway && j.gateway.port;
      process.stdout.write(typeof p === 'number' ? String(p) : '18789');
    } catch (e) { process.stdout.write('18789'); }
  " 2>/dev/null) || GATEWAY_PUBLIC_PORT=18789
else
  echo "WARNING: $OC_CONFIG not found; defaulting gateway.port to 18789"
  GATEWAY_PUBLIC_PORT=18789
fi
GATEWAY_BACKEND_PORT=$((GATEWAY_PUBLIC_PORT + 1))

echo "Public port  (proxy):   $GATEWAY_PUBLIC_PORT  ← Caddy + clients"
echo "Backend port (gateway): $GATEWAY_BACKEND_PORT  ← openclaw process"

# ─── Build and test ──────────────────────────────────────────────────────────
echo "--- npm install"
npm install
echo "--- npm run build"
npm run build
echo "--- npm test"
npm test

# ─── Deploy skill ────────────────────────────────────────────────────────────
mkdir -p "$SKILL_DEST"
cp -r "$REPO_ROOT/skills/router-governor/"* "$SKILL_DEST/"
echo "--- Deployed skill to $SKILL_DEST"

# ─── Env files ───────────────────────────────────────────────────────────────
cat > "$ENV_FILE" << EOF
# Router-governor env (shell) — generated by scripts/post-pull-activate.sh — do not edit by hand
export OPENCLAW_HOME="$OPENCLAW_HOME"
export ROUTER_GOVERNOR_POLICY_PATH="$REPO_ROOT/config/policy.json"
# Log path defaults to OPENCLAW_HOME/logs/model-governor.jsonl
EOF

cat > "$SYSTEMD_ENV_FILE" << EOF
OPENCLAW_HOME=$OPENCLAW_HOME
ROUTER_GOVERNOR_POLICY_PATH=$REPO_ROOT/config/policy.json
EOF
echo "--- Wrote env files"

# ─── run-gateway.sh (single source of truth: reads openclaw.json at start time) ─
# Runs openclaw gateway on backend port (gateway.port + 1). Cross-platform: openclaw from PATH, else node resolve, else common paths (Linux/macOS).
cat > "$GATEWAY_SCRIPT" << 'GWEOF'
#!/bin/sh
# Run openclaw gateway on (gateway.port + 1) so the router-governor proxy owns gateway.port.
# Single source of truth: openclaw.json → gateway.port.
CONFIG="${OPENCLAW_CONFIG_PATH:-${OPENCLAW_HOME:-$HOME/.openclaw}/openclaw.json}"
PUBLIC_PORT=$(node -e "
  try {
    const j = require(\"$CONFIG\");
    const p = j.gateway && j.gateway.port;
    process.stdout.write(typeof p === 'number' ? String(p) : '18789');
  } catch (e) { process.stdout.write('18789'); }
" 2>/dev/null) || PUBLIC_PORT=18789
BACKEND_PORT=$((PUBLIC_PORT + 1))

# Prefer openclaw CLI on PATH (works for npm i -g openclaw, npx, brew, etc.)
if command -v openclaw >/dev/null 2>&1; then
  exec openclaw gateway --port "$BACKEND_PORT"
fi

# Else resolve openclaw from Node (global or current node_modules)
OPENCLAW_ENTRY=$(node -e "
  try {
    const p = require.resolve('openclaw/package.json');
    const path = require('path');
    process.stdout.write(path.join(path.dirname(p), 'dist', 'index.js'));
  } catch (e) {}
" 2>/dev/null)
if [ -n "$OPENCLAW_ENTRY" ] && [ -f "$OPENCLAW_ENTRY" ]; then
  exec node "$OPENCLAW_ENTRY" gateway --port "$BACKEND_PORT"
fi

# Fallback: common install paths (Ubuntu/Debian, macOS Homebrew, Linux /usr/local)
for base in /usr/lib/node_modules/openclaw /usr/local/lib/node_modules/openclaw /opt/homebrew/lib/node_modules/openclaw; do
  if [ -f "$base/dist/index.js" ]; then
    exec node "$base/dist/index.js" gateway --port "$BACKEND_PORT"
  fi
done

echo "openclaw not found. Install it (npm i -g openclaw, or system package) or ensure OPENCLAW_HOME is set." >&2
exit 1
GWEOF
chmod +x "$GATEWAY_SCRIPT"
echo "--- Wrote $GATEWAY_SCRIPT"

# ─── validate-gateway-proxy.sh ───────────────────────────────────────────────
# Port checks: ss (Linux) or lsof (macOS). Caddy paths include Homebrew.
cat > "$VALIDATE_SCRIPT" << 'VEOF'
#!/bin/sh
# Validate the router-governor proxy → openclaw gateway → Caddy port chain.
# Works on Linux (ss) and macOS (lsof).
CONFIG="${OPENCLAW_CONFIG_PATH:-${OPENCLAW_HOME:-$HOME/.openclaw}/openclaw.json}"
PUBLIC=$(node -e "
  try { const j=require(\"$CONFIG\"); process.stdout.write(String(j.gateway&&j.gateway.port||18789)); }
  catch(e){ process.stdout.write('18789'); }
" 2>/dev/null) || PUBLIC=18789
BACKEND=$((PUBLIC + 1))
FAIL=0

# Port listening check: Linux (ss) or macOS (lsof)
port_listening() {
  p="$1"
  if command -v ss >/dev/null 2>&1; then
    ss -tlnp 2>/dev/null | grep -q ":${p}[^0-9]"
    return $?
  fi
  if command -v lsof >/dev/null 2>&1; then
    lsof -iTCP:${p} -sTCP:LISTEN -t 2>/dev/null | grep -q .
    return $?
  fi
  return 1
}

echo "Config:  $CONFIG  (gateway.port = $PUBLIC)"
echo "Chain:   Caddy → proxy :$PUBLIC → gateway :$BACKEND"
echo ""

# Unsupported key: agents.defaults.skills (OpenClaw rejects it; gateway won't start)
if [ -n "$CONFIG" ] && [ -f "$CONFIG" ]; then
  if CONFIG="$CONFIG" node -e '
    try {
      const j = require(process.env.CONFIG);
      const s = j && j.agents && j.agents.defaults && j.agents.defaults.skills;
      process.exit(typeof s !== "undefined" ? 0 : 1);
    } catch (e) { process.exit(1); }
  ' 2>/dev/null; then
    echo "  [FAIL] openclaw.json contains agents.defaults.skills (unsupported; gateway will not start)"
    echo "         Remove that key (e.g. openclaw doctor --fix or edit manually), then restart gateway."
    FAIL=1
  fi
fi

# Proxy
if port_listening "$PUBLIC"; then
  echo "  [OK]   proxy listening on :$PUBLIC"
else
  echo "  [FAIL] proxy not listening on :$PUBLIC"
  FAIL=1
fi
# Gateway
if port_listening "$BACKEND"; then
  echo "  [OK]   gateway listening on :$BACKEND"
else
  echo "  [FAIL] gateway not listening on :$BACKEND"
  FAIL=1
fi
# Caddy (Linux and macOS Homebrew paths)
CADDY_OK=0
for CF in /etc/caddy/Caddyfile /usr/local/etc/caddy/Caddyfile /opt/homebrew/etc/Caddyfile; do
  [ -f "$CF" ] || continue
  if grep -q "reverse_proxy.*127\.0\.0\.1:${PUBLIC}[^0-9]" "$CF" 2>/dev/null; then
    echo "  [OK]   Caddy ($CF) → :$PUBLIC"
    CADDY_OK=1
  else
    ACTUAL=$(grep -o 'reverse_proxy [^ {:]*' "$CF" 2>/dev/null | head -1 | awk '{print $2}')
    echo "  [FAIL] Caddy ($CF) → $ACTUAL (expected 127.0.0.1:$PUBLIC)"
    FAIL=1
  fi
done
[ "$CADDY_OK" -eq 0 ] && echo "  [SKIP] Caddy not found or no Caddyfile"

# Health endpoint
HEALTH=$(curl -s --max-time 2 "http://127.0.0.1:${PUBLIC}/health" 2>/dev/null || echo "")
if echo "$HEALTH" | grep -q '"status":"ok"'; then
  echo "  [OK]   proxy /health"
else
  echo "  [WARN] proxy /health returned: $HEALTH"
fi

echo ""
[ "$FAIL" -eq 0 ] && echo "All checks passed." || echo "Fix the failures above."
exit $FAIL
VEOF
chmod +x "$VALIDATE_SCRIPT"
echo "--- Wrote $VALIDATE_SCRIPT"

# ─── systemd wiring (Linux) or LaunchAgents (macOS) ───────────────────────────
NODE_BIN="$(command -v node 2>/dev/null || echo 'node')"
OS="$(uname -s)"

if [ "$OS" = "Linux" ]; then
  if ! systemctl --user status openclaw-gateway.service >/dev/null 2>&1; then
    echo "--- openclaw-gateway.service not found; skipping systemd wiring"
  else
  # Refuse to activate if openclaw.json contains unsupported agents.defaults.skills (gateway won't start)
  if [ -f "$OC_CONFIG" ]; then
    if node -e "
      try {
        const j = require('$OC_CONFIG');
        const s = j && j.agents && j.agents.defaults && j.agents.defaults.skills;
        process.exit(typeof s !== 'undefined' ? 0 : 1);
      } catch (e) { process.exit(1); }
    " 2>/dev/null; then
      echo "ERROR: $OC_CONFIG contains agents.defaults.skills. OpenClaw does not support this key; the gateway will not start."
      echo "Remove it (e.g. openclaw doctor --fix or edit manually), then run npm run activate again."
      exit 1
    fi
  fi

  OVERRIDE_DIR="$HOME/.config/systemd/user/openclaw-gateway.service.d"
  OVERRIDE_FILE="$OVERRIDE_DIR/override.conf"
  mkdir -p "$OVERRIDE_DIR"

  # Strip lines we own; preserve hand-crafted lines from the existing override
  if [ -f "$OVERRIDE_FILE" ]; then
    awk '
      /^\s*ExecStart=/                    { next }
      /^\s*EnvironmentFile=.*router-governor/ { next }
      /^\s*Environment=OPENCLAW_GATEWAY_PORT=/ { next }
      { print }
    ' "$OVERRIDE_FILE" > "${OVERRIDE_FILE}.tmp"
    mv "${OVERRIDE_FILE}.tmp" "$OVERRIDE_FILE"
  else
    printf "[Service]\n" > "$OVERRIDE_FILE"
  fi

  # Append our controlled lines
  cat >> "$OVERRIDE_FILE" << EOV
EnvironmentFile=-$SYSTEMD_ENV_FILE
# ExecStart= clears the main unit's ExecStart (systemd requires exactly one)
ExecStart=
ExecStart=$GATEWAY_SCRIPT
EOV

  systemctl --user daemon-reload
  systemctl --user restart openclaw-gateway.service
  echo "--- Gateway restarted (port $GATEWAY_BACKEND_PORT via $GATEWAY_SCRIPT)"

  # ─── Proxy service ───────────────────────────────────────────────────────
  PROXY_UNIT="$HOME/.config/systemd/user/openclaw-gateway-proxy.service"
  PROXY_OVERRIDE_DIR="$HOME/.config/systemd/user/openclaw-gateway-proxy.service.d"
  mkdir -p "$PROXY_OVERRIDE_DIR"

  # Write proxy unit with concrete paths and ports (re-generated each time)
  cat > "$PROXY_UNIT" << PEOF
[Unit]
Description=OpenClaw Gateway Proxy (router-governor)
After=openclaw-gateway.service

[Service]
Environment=OPENCLAW_GATEWAY_PROXY_PORT=$GATEWAY_PUBLIC_PORT
Environment=OPENCLAW_GATEWAY_BACKEND_URL=http://127.0.0.1:$GATEWAY_BACKEND_PORT
WorkingDirectory=$REPO_ROOT
ExecStart=$NODE_BIN $REPO_ROOT/dist/src/gateway-proxy.js
Restart=always
RestartSec=5

[Install]
WantedBy=default.target
PEOF

  printf "[Service]\nEnvironmentFile=-%s\n" "$SYSTEMD_ENV_FILE" > "$PROXY_OVERRIDE_DIR/override.conf"
  systemctl --user daemon-reload
  systemctl --user enable openclaw-gateway-proxy.service
  systemctl --user restart openclaw-gateway-proxy.service
  echo "--- Proxy restarted (port $GATEWAY_PUBLIC_PORT → backend $GATEWAY_BACKEND_PORT)"
  fi
fi

# ─── macOS: LaunchAgent plists (gateway + proxy) ──────────────────────────────
if [ "$OS" = "Darwin" ]; then
  LAUNCH_AGENTS="${HOME}/Library/LaunchAgents"
  mkdir -p "$LAUNCH_AGENTS"

  # Gateway: run run-gateway.sh with env from systemd-style env file
  GATEWAY_PLIST="$LAUNCH_AGENTS/com.openclaw.router-governor.gateway.plist"
  cat > "$GATEWAY_PLIST" << PLISTGW
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>com.openclaw.router-governor.gateway</string>
  <key>ProgramArguments</key>
  <array>
    <string>$GATEWAY_SCRIPT</string>
  </array>
  <key>EnvironmentVariables</key>
  <dict>
    <key>OPENCLAW_HOME</key>
    <string>$OPENCLAW_HOME</string>
    <key>OPENCLAW_CONFIG_PATH</key>
    <string>$OC_CONFIG</string>
  </dict>
  <key>RunAtLoad</key>
  <false/>
  <key>KeepAlive</key>
  <true/>
  <key>StandardOutPath</key>
  <string>/tmp/openclaw-gateway.log</string>
  <key>StandardErrorPath</key>
  <string>/tmp/openclaw-gateway.err</string>
</dict>
</plist>
PLISTGW
  echo "--- Wrote $GATEWAY_PLIST (load with: launchctl load $GATEWAY_PLIST)"

  # Proxy: node gateway-proxy.js from repo
  PROXY_PLIST="$LAUNCH_AGENTS/com.openclaw.router-governor.proxy.plist"
  cat > "$PROXY_PLIST" << PLISTPX
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>com.openclaw.router-governor.proxy</string>
  <key>ProgramArguments</key>
  <array>
    <string>$NODE_BIN</string>
    <string>$REPO_ROOT/dist/src/gateway-proxy.js</string>
  </array>
  <key>EnvironmentVariables</key>
  <dict>
    <key>OPENCLAW_GATEWAY_PROXY_PORT</key>
    <string>$GATEWAY_PUBLIC_PORT</string>
    <key>OPENCLAW_GATEWAY_BACKEND_URL</key>
    <string>http://127.0.0.1:$GATEWAY_BACKEND_PORT</string>
    <key>OPENCLAW_HOME</key>
    <string>$OPENCLAW_HOME</string>
    <key>ROUTER_GOVERNOR_POLICY_PATH</key>
    <string>$REPO_ROOT/config/policy.json</string>
  </dict>
  <key>WorkingDirectory</key>
  <string>$REPO_ROOT</string>
  <key>RunAtLoad</key>
  <false/>
  <key>KeepAlive</key>
  <true/>
  <key>StandardOutPath</key>
  <string>/tmp/openclaw-gateway-proxy.log</string>
  <key>StandardErrorPath</key>
  <string>/tmp/openclaw-gateway-proxy.err</string>
</dict>
</plist>
PLISTPX
  echo "--- Wrote $PROXY_PLIST (load with: launchctl load $PROXY_PLIST)"
  echo "--- macOS: Start gateway and proxy with: launchctl load $GATEWAY_PLIST && launchctl load $PROXY_PLIST"
fi

# ─── Caddy: ensure it points to the proxy port (not the backend) ─────────────
# Linux and macOS Homebrew paths
for CADDYFILE in /etc/caddy/Caddyfile /usr/local/etc/caddy/Caddyfile /opt/homebrew/etc/Caddyfile; do
  [ -f "$CADDYFILE" ] || continue
  NEEDS_RELOAD=0
  # If Caddy is pointing directly at the backend port, redirect it to the proxy port
  if grep -q "reverse_proxy.*127\.0\.0\.1:${GATEWAY_BACKEND_PORT}" "$CADDYFILE"; then
    sed -i "s|reverse_proxy 127\.0\.0\.1:${GATEWAY_BACKEND_PORT}|reverse_proxy 127.0.0.1:${GATEWAY_PUBLIC_PORT}|g" "$CADDYFILE"
    echo "--- Updated Caddy ($CADDYFILE): :$GATEWAY_BACKEND_PORT → :$GATEWAY_PUBLIC_PORT"
    NEEDS_RELOAD=1
  elif grep -q "reverse_proxy.*127\.0\.0\.1:${GATEWAY_PUBLIC_PORT}" "$CADDYFILE"; then
    echo "--- Caddy ($CADDYFILE) already points to :$GATEWAY_PUBLIC_PORT [OK]"
  else
    echo "--- WARNING: Caddy found at $CADDYFILE but no matching reverse_proxy; check manually"
  fi
  if [ "$NEEDS_RELOAD" -eq 1 ]; then
    if command -v caddy >/dev/null 2>&1 && caddy reload --config "$CADDYFILE" 2>/dev/null; then
      echo "--- Caddy reloaded"
    elif systemctl reload caddy 2>/dev/null; then
      echo "--- Caddy reloaded (systemctl)"
    else
      echo "--- WARNING: Caddy reload failed; run: systemctl reload caddy"
    fi
  fi
done

echo ""
echo "Activation complete."
echo "  proxy  :$GATEWAY_PUBLIC_PORT  → governor (router) or forward to gateway"
echo "  gateway:$GATEWAY_BACKEND_PORT ← proxy forwards non-router traffic"
echo "  Caddy  → :$GATEWAY_PUBLIC_PORT (proxy)"
echo "  Validate: $VALIDATE_SCRIPT"
echo "  Logs:     source $ENV_FILE && npm run log:report"
